version: '3.7'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: es01
    volumes:
      # - type: bind
      #   source: ./elastic-stack-ca.p12
      #   target: /usr/share/elasticsearch/config/elastic-stack-ca.p12
      #   read_only: true
      - type: volume
        source: elasticsearch1
        target: /usr/share/elasticsearch
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      # - xpack.security.transport.ssl.enabled=true
      # - xpack.security.transport.ssl.verification_mode=none
      # - xpack.security.transport.ssl.keystore.path=/usr/share/elasticsearch/config/elastic-certificates.p12
      # - xpack.security.transport.ssl.truststore.path=/usr/share/elasticsearch/config/elastic-certificates.p12
      - ELASTIC_PASSWORD=password
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
    networks:
      - elastic

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: es02
    volumes:
      # - type: bind
      #   source: ./elastic-stack-ca.p12
      #   target: /usr/share/elasticsearch/config/elastic-stack-ca.p12
      #   read_only: true
      - type: volume
        source: elasticsearch2
        target: /usr/share/elasticsearch
    environment:
      - node.name=es02
      - cluster.name=docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      # - xpack.security.transport.ssl.enabled=true
      # - xpack.security.transport.ssl.verification_mode=none
      # - xpack.security.transport.ssl.keystore.path=/usr/share/elasticsearch/config/elastic-certificates.p12
      # - xpack.security.transport.ssl.truststore.path=/usr/share/elasticsearch/config/elastic-certificates.p12
      - ELASTIC_PASSWORD=password
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    networks:
      - elastic

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: es03
    volumes:
      # - type: bind
      #   source: ./elastic-stack-ca.p12
      #   target: /usr/share/elasticsearch/config/elastic-stack-ca.p12
      #   read_only: true
      - type: volume
        source: elasticsearch3
        target: /usr/share/elasticsearch
    environment:
      - node.name=es03
      - cluster.name=docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      # - xpack.security.transport.ssl.enabled=true
      # - xpack.security.transport.ssl.verification_mode=none
      # - xpack.security.transport.ssl.keystore.path=/usr/share/elasticsearch/config/elastic-certificates.p12
      # - xpack.security.transport.ssl.truststore.path=/usr/share/elasticsearch/config/elastic-certificates.p12
      - ELASTIC_PASSWORD=password
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    networks:
      - elastic

  kibana:
    image: kibana:7.9.2
    container_name: kibana
    ports:
      - '5601:5601'
    volumes:
      - /root/docker-elk/kibana.yml:/usr/share/kibana/config/kibana.yml
    restart: always
    networks:
      - elastic
 
#  logstash:
#    image: logstash:7.9.2
#    container_name: logstash
#    ports:
#      - '5000:5000'
    #volumes:
    #  - type: bind
    #    source: ./logstash_pipeline/
    #    target: /usr/share/logstash/pipeline
    #    read_only: true
#    restart: always    
#    networks:
#      - elastic
networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch1:
  elasticsearch2:
  elasticsearch3:
